### PR TITLE
Fixed Package VC, Legal Entity Evidence Document, Packing List VC

### PR DESCRIPTION
**Pull request by aaorlov**
Fixed the following schemas by deconstruction and creating new or updating associated tests for:
- Package VC
- Legal Entity Evidence Document
- Packing List VC

### CODE REVIEW

**Comment by OR13** [comment]
We need CI to be running on PRs like this, way to many changes to merge without checks.

**Review by OR13 — CHANGES_REQUESTED** [review]
Need proof that CI is passing in order to merge PRs from forks.

**Comment by mprorock** [comment]
Agreed

**Review by mprorock — CHANGES_REQUESTED** [review]
CI must be passing

**Comment by OR13** [comment]
@mprorock does this look like a solution to this issue https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target

I think we want to know when a PR from a forked repo is going to break things... on this PR ... without checking commits on the fork...

**Comment by Therecanbeonlyone1969** [comment]
@OR13 @mprorock @mkhraisha ... CI passes now. https://github.com/cstoecker/traceability-vocab/runs/1955823847

I had forgotten to update my PackingList credential VC test after updating and testing the schemas (urrrgh) and the bill of lading VC test (not mine!!!) failed because the bol.json in the __fixture__ had `orderNumber` instead of `purchaseNumber` as it should be because that is defined in Purchase.json.

**Review by mprorock — APPROVED** [review]

**Review by mkhraisha — APPROVED** [review]

**Review by OR13 — APPROVED** [review]

**Pull request merged**
