### PR TITLE
Packing list updates

### PR DESCRIPTION
**Pull request by nissimsan**
Refactored the Packing List based on this sample, added as example. 

packing-list-ex

### CODE REVIEW

**Comment by TallTed** [comment]
That is one mighty hand-crafted sample, only separated from hand-written by the use of Excel or other spreadsheet, *probably* primarily done to eliminate problems of illegible hand-writing!  Eliminating that sort of thing should definitely be a goal of this process...

In the meantime -- it would probably be useful to collect as many pre-printed forms as possible, distinctly from this sort of hand-crafted blank-page fake-form, and focus first on covering those pre-printed forms, which the hand-crafted versions are already imitating.

Otherwise, we're formalizing informal versions of formality, and risk omitting significant formalities which are already forgotten, distorted, or otherwise contaminated by the manual process.

**Comment by nissimsan** [comment]
It's reality, @TallTed - this is the world we live in!  :)

**Review by mprorock — APPROVED** [review]
Cleans up a lot of cruft and standardizes in a way that can be used cross market sector

**Review by OR13 — APPROVED** [review]

**Comment by TallTed** [comment]
"by ACRE AGE IS THE NEW BLACK" in the first column!  :-)

**Pull request merged**
