### PR TITLE
Feature/generator cleanup

### PR DESCRIPTION
**Pull request by mprorock**
@OR13 @Therecanbeonlyone1969 @mkhraisha I will be touching the following items today unless you say otherwise.  After this pass I will ensure that full generation through to issued VC example should be in for *most* of all listed schemas automatically, assuming that they have a generator.  I also will be addressing any items that have frequent data changes on generation that clutter up the build.  Please comment on this PR while in draft mode for anything you want to carve off and cover in your own PR.

Once we get to that point, with VC examples for everything, clean generation and validation, i am going to suggest we tag a version.

Generators that are too dynamic with data - these will get addressed first as they are currently mucking up fixtures with changes:

- [x]  LEIregistration
- [x] EcommerceWayBillRegistrationEvidenceDocument

Secondary offendors to this list:
- [x] LEIentity
- [x] LEIevidenceDocument
- [x] ShippingStop
- [x] ProductRegistrationEvidenceDocument
- [x] EcommerceBindingDataRegistrationCredential
- [x] EcommerceInvoiceRegistrationEvidenceDocument
- [x] EcommerceOrderRegistrationEvidenceDocument
- [x] EcommerceWayBillRegistrationCredential

Generators that mostly work but have now validation issues not currently handled (e.g. support for additional fields, allOf use, etc.):
- [x] AgActivity
- [x] AgInspectionReport
- [x] AgParcelDelivery
- [x] UsdaSc6
- [x] ppq203
- [x] ppq587

Generators that are absent or entirely broken:
- [ ] BillOfLading
- [ ] BillOfLadingCredential
- [x] CertifidMillTestReportCredential
- [ ] CommercialInvoiceCredential
- [ ] CrudeOilProduct
- [ ] QPInbond

### CODE REVIEW

**Comment by Therecanbeonlyone1969** [comment]
@mprorock ... what does "too dynamic with data mean" from your PoV? I was under the impression we want to gen everything dynamically.

**Comment by mprorock** [comment]
@Therecanbeonlyone1969 fixtures should be more or less fixed unless adding a new type, issue is that if dates for instance change when running the build, then fixtures that you did not actually touch as a part of your commit will be updated and the number of changed files will grow rapidly making it difficult if not impossible to review the actual changes that are being made.

**Comment by mprorock** [comment]
@Therecanbeonlyone1969 basically we want the spec and all data to generate dynamically, but if there is no change to an object it should be repeatable.  the big offender on this is the way faker handles dates, that is the one item that random seeds don't really affect if you use past / present / future with faker

**Comment by Therecanbeonlyone1969** [comment]
@mprorock ... we could hardcode dates in the generators and not use faker ... that should not be an issue. I think what you are saying is that CI/CD should only run on new or changed schemas/generators and not the rest ... I think that is an issue we should address but not by making things less dynamic. I am not deep enough into devops but I would say that .gitignore should be updated based on committed changes, no? so that is a module we can create. thoughts? cc @OR13

**Comment by mprorock** [comment]
@Therecanbeonlyone1969 - no.  CI / CD runs on everything, and docs / spec / credentials are tested and re-generated with each run.  

basically, the `__fixtures__` folder should only see changes when:
- a new object is added (and then a folder for that object will appear, along with test fixtures)
- an object is actually changed
- something upstream from an object changed

I have already corrected the bulk of this.  There is now a master generators singleton in utils to provide consistent dates for use in generators, as well as a master instance of faker with a set seed.

**Comment by mprorock** [comment]
going to convert this soon.  This addresses the date issues (as best i can tell) as well as fixes a lot of semi busted stuff.

I have stubbed or also made some adjustments in the following:
BillOfLading
CertifidMillTestReport
CommercialInvoice
CrudeOilProduct
QPInbond

A key note:  the schema is the master, so having a credential in the schemas doesn't really make sense, as the credential and then verified credential will get built automagically and programatically.  I am going to be going through and building out some saner generation on all the ag stuff to prevent fixutures from changing unless an upstream item changed, but will likely do this after plugfest.

jumping over to #135 now

**Review by OR13 — APPROVED** [review]

**Pull request merged**
