### PR TITLE
Rename to "Certification of Origin"

### PR DESCRIPTION
**Pull request by nissimsan**
Based on feedback from DHS, changing from "Certificate of Origin" to "Certification of Origin".

### CODE REVIEW

**Review by mprorock — APPROVED** [review]

**Comment by nissimsan** [comment]
Changing this to Draft. We're confirming if `Certification` is indeed a better term.

**Comment by mprorock** [comment]
> Changing this to Draft. We're confirming if `Certification` is indeed a better term.

we are OK either way - "Certificate of Origin" we encounter more often in Ag

**Review by BenjaminMoe — APPROVED** [review]

**Comment by nissimsan** [comment]
> > Changing this to Draft. We're confirming if `Certification` is indeed a better term.
> 
> we are OK either way - "Certificate of Origin" we encounter more often in Ag

Yes, "Certificate" is also the prevalent term in shipping and what I am used to. But we confirmed "Certification" with CBP now so let's go for that.

**Review by mkhraisha — APPROVED** [review]

**Comment by nissimsan** [comment]
Let me look into why the file delete is not here. 
Merging offline.

**Comment by nissimsan** [comment]
Fixed. Merging.

**Pull request merged**
