### PR TITLE
fix: bugs

### PR DESCRIPTION
**Pull request by nissimsan**
Syntax bugs and @vocab deletion

### CODE REVIEW

**Comment by rhofvendahl** [comment]
@nissimsan 

I only saw this after creating https://github.com/w3c-ccg/traceability-vocab/pull/317, & it looks like you've addressed a few of the same bugs. Once this is merged I'll update my PR so it doesn't conflict with these changes.

**Review by mkhraisha — APPROVED** [review]
Looks great!

**Comment by nissimsan** [comment]
@rhofvendahl - thank you!! 

I was forced to introduce those `@vocab`s in the interim period before we had [this tool](https://github.com/w3c-ccg/traceability-vocab/tree/main/packages/traceability-schemas/data). It's been bugging me ever since, causing annoying side effects (you might have noticed). Typical that we just decided to pick that up at essentially the same time! :D

Thanks again! If you're on the call tomorrow we'll get to it then too.

**Comment by TallTed** [comment]
@nissimsan -- Please edit the initial comment on this PR, to codefence `@vocab` (yes, another github user we needlessly `@` ping when writing too quickly...)

**Review by OR13 — APPROVED** [review]

**Pull request merged**
