### PR TITLE
Add support for JSON Patch

### PR DESCRIPTION
**Pull request by OR13**
Spec text (would need a lot more to safely explain this).

Screen Shot 2023-06-22 at 10 06 50 AM

What a graph that contains operations looks like:

Screen Shot 2023-06-22 at 9 54 30 AM

What the simple solution we already have looks like

Screen Shot 2023-06-21 at 2 08 07 PM

### CODE REVIEW

**Comment by OR13** [comment]
I don't think we should proceed with this approach, it adds a lot of complexity to both holders and verifiers, and it destroys the value of graph queries over presented data.

**Comment by mprorock** [comment]
> I don't think we should proceed with this approach, it adds a lot of complexity to both holders and verifiers, and it destroys the value of graph queries over presented data.

@brownoxford I think this is going to be way more complex than needed 

@OR13 perhaps there is a solution where we use the operations as defined by json patch, but provide the new credentials as payload?

**Comment by mkhraisha** [comment]
I believe this PR is too complex, and the existing solution is fine until we can get consensus on a mandatory credential ID

**Comment by OR13** [comment]
I am going to close this PR, the discussion has been had, and we should not take this path.

I will leave it open for 1 more pass before closing it.

**Comment by nissimsan** [comment]
Not a viable direction. Direction on the call to abandon this. Let's take it up next week before dismissing.

**Comment by OR13** [comment]
As discussed, we are closing this PR.

**Pull request closed without merging**
