### PR TITLE
Add required fields to all credentials

### PR DESCRIPTION
**Pull request by BenjaminMoe**
This PR updates all credentials to include a list of required attributes.

### CODE REVIEW

**Review by mkhraisha — APPROVED** [review]

**Comment by BenjaminMoe** [comment]
Notes from call: remove `id` from required for pull request.

**Review by mkhraisha — APPROVED** [review]
happy to have this included as long as we add the "id" to a section on the respec doc, OR we remove id.

**Comment by BenjaminMoe** [comment]
https://github.com/w3c-ccg/traceability-vocab/issues/596

**Comment by BenjaminMoe** [comment]
```
  console.error
    VerifiablePostmanCollection 
     [
      {
        keyword: 'additionalProperties',
        dataPath: '',
        schemaPath: '#/additionalProperties',
        params: { additionalProperty: 'issuer' },
        message: 'should NOT have additional properties'
      }
    ]

    VerifiableScorecard 
     [
      {
        keyword: 'additionalProperties',
        dataPath: '',
        schemaPath: '#/additionalProperties',
        params: { additionalProperty: 'issuer' },
        message: 'should NOT have additional properties'
      }
    ]
```

**Pull request merged**
