### PR TITLE
add mahmoud to editor list

### PR DESCRIPTION
**Pull request by mkhraisha**
PR to add myself to the Editor Spec document.

on a further note I don't seem to have the Shield when reviewing PRs, last time this was brought up I believe the fix was to add me as an editor to the repo @OR13

### CODE REVIEW

**Review by OR13 — APPROVED** [review]

**Comment by OR13** [comment]
@mkhraisha says you have not accepted the "editor invite" in github

**Comment by OR13** [comment]
@mkhraisha please fix merge conf.

**Comment by mkhraisha** [comment]
> @mkhraisha says you have not accepted the "editor invite" in github

would you be able to resend the invite? I haven't received/can't seem to find it.

**Comment by OR13** [comment]
@mkhraisha sent again.

**Pull request merged**
