### PR TITLE
fix: address linting errors in respec document

### PR DESCRIPTION
**Pull request by BenjaminMoe**
Addresses linting errors in respec document. Large changes are result of auto-formatting in VS code.
One of the errors was a broken local link, the other errors were all `<dfn>` tags that were never linked to. 

Screenshot 2022-03-17 at 05-03-19 Traceability Vocabulary v0 0

### CODE REVIEW

**Review by OR13 — APPROVED** [review]

**Review by nissimsan — APPROVED** [review]

**Comment by BenjaminMoe** [comment]
Save without formatting (once that's done, good to merge)

**Comment by mkhraisha** [comment]
Good to merge pending removal of formatting changes.

**Comment by BenjaminMoe** [comment]
Restored the index.html from main and re-implemented without auto-formatting.

**Comment by nissimsan** [comment]
Looks good, @BenjaminMoe! Merging.

**Pull request merged**
