### PR TITLE
MTR shipto optionality

### PR DESCRIPTION
**Pull request by nissimsan**
Optional elements should not contain mandatory child elements.

### CODE REVIEW

**Review by mkhraisha — APPROVED** [review]

**Review by OR13 — APPROVED** [review]

**Comment by TallTed** [comment]
> Optional elements should not contain mandatory child elements.

Would these not be conditionally mandatory?  That is, if an optional element is present, it must contain specified child elements. If the optional element is not present, those child elements are not required because their parent element is not present...

**Comment by mkhraisha** [comment]
Can we add the "optional mandatory fields" into the description of the PR and merge it in out of band.

**Comment by brownoxford** [comment]
Would it not be better to leave these in and add comments indicating that they should be commented out if you use one of the broken tools?

**Comment by TallTed** [comment]
Most (probably all) instances of "Conditionally mandatory if..." would be better just "Mandatory if..."

**Pull request merged**
