### PR TITLE
to add note about process VCs in eComm use case

### PR DESCRIPTION
**Pull request by bumblefudge**
Down payment on #64 -- to be updated once process VCs multiply and again if/when process VCs get segregrated in a subfolder, prefixed, etc.

### CODE REVIEW

**Comment by bumblefudge** [comment]
(happy to leave this open or close it and re-open later when there's more to do on this front.)

**Review by mprorock — APPROVED** [review]
I am OK with this for now - ultimately we will want to get this stuff resolved, then we can pull this note. It is however quite helpful for now.  if we get some tagging added to objects we can classify these types of items and then they will be less problematic

**Comment by OR13** [comment]
@bumblefudge I think this is the best related issue to this: https://github.com/w3c-ccg/traceability-vocab/issues/24#issuecomment-840054844

if you want to add a respec issue link, you can do so like this:

```
   <p class="issue" data-number="24">
     Contributors are discussing how best to categorize process or event credentials vs product or organization credentials
    </p>
```

**Review by mkhraisha — APPROVED** [review]

**Comment by OR13** [comment]
6 days open, multiple approvals, merging

**Pull request merged**
