### PR TITLE
E-Commerce Order & Invoice - Untested

### PR DESCRIPTION
**Pull request by cstoecker**
Sample VCs  and Schemas for Order and Invoice

Test and test vector creation will be done now as well

Co-Authored-By: Andreas Freund <20665612+Therecanbeonlyone1969@users.noreply.github.com>

### CODE REVIEW

**Review by mprorock — CHANGES_REQUESTED** [review]
as soon as test vectors are added and all tests are passing will merge

**Comment by OR13** [comment]
This PR is blocked pending test vectors.

**Review by OR13 — CHANGES_REQUESTED** [review]
json files should have `.json` file extension

**Comment by cstoecker** [comment]
Order & invoice will be move into a new PR including all test vectors.

**Comment by cstoecker** [comment]
Order & invoice will be move into a new PR including all test vectors.

**Pull request closed without merging**
