### PR TITLE
Update Respec Documentation

### PR DESCRIPTION
**Pull request by BenjaminMoe**
This PR updates the documentation for readability.

- Credentials were split off into their own section
- Example documents were moved to their credential definition
- Workflow was changed to link to credentials
- Link to API spec is included in Section 1
- Reference images appear with the document they support

### CODE REVIEW

**Review by nissimsan — APPROVED** [review]
Absolutely beautiful!!

**Comment by nissimsan** [comment]
@BenjaminMoe, should `packages/traceability-schemas/scripts/descriptions.json` ideally be placed somewhere under `docs/` instead. It really is mostly "business content", linking schemas with examples, both of which are also under /docs. 
This is minor, let's get it merged and move it later.

**Comment by BenjaminMoe** [comment]
The `descriptions.json` file is a patch. It seems like the easiest way to get the desired effect without making any major changes. We can move the references images to the schema files and find an alternative in a later PR. I can make an issue if needed.

**Comment by BenjaminMoe** [comment]
Note: I think closing this in favor of a cleaner implementation.

**Comment by BenjaminMoe** [comment]
This PR has been replaced by https://github.com/w3c-ccg/traceability-vocab/pull/364 which takes a more restrained approach to updating the Respec document. Closing.

**Pull request closed without merging**
